#
# docker compose file for testing OpenL2M.
# Note: this is NOT meant to become a production setup!!!
#
# set name for deterministic container names:
name: openl2m-testing

services:
  postgres:
    image: postgres:16.2-alpine3.19
    # no public mapping of postgres.
    # ports:
    #   - 5432:5432
    # expose postgress port to internal services only:
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=openl2m
      - POSTGRES_DB=openl2m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openl2m"]
      interval: 5s
      timeout: 5s
      retries: 5

  openl2m:
    image: openl2m:test-build
    build:
      dockerfile: ./Dockerfile
    environment:
      - DB_USER=openl2m
      - DB_NAME=openl2m
      - DB_HOST=postgres
      # so we can sense easily that we are running in container:
      - IN_CONTAINER=1
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

volumes:
  postgres_data:
